### ISSUE TITLE
Especificación formal

### ISSUE THREAD

**Issue by Lorenacalvoperez** [JuliaArellano/PRACTICA_3#1]
Realización de la especificación formal de cada uno de los casos de usos que se han identificados y rellenar la siguiente tabla:

![image](https://github.com/JuliaArellano/PRACTICA_3/assets/127235680/f2a4c735-ce60-4344-80a9-d91cd2fc6bb2)
![image](https://github.com/JuliaArellano/PRACTICA_3/assets/127235680/d62d3ad5-aca4-4fe5-ae94-e8034e53d6cd)

**Comment by pgl1005** [comment]
He hecho este caso de uso, que os parece?
<img width="407" alt="image" src="https://github.com/JuliaArellano/PRACTICA_3/assets/127233991/57551a17-0690-4ed7-aff8-7d51324235a7">

**Comment by JuliaArellano** [comment]
![image](https://github.com/JuliaArellano/PRACTICA_3/assets/127235682/0fb6c072-2acd-42f3-aec3-18a7a0936062)

**Comment by JuliaArellano** [comment]
![image](https://github.com/JuliaArellano/PRACTICA_3/assets/127235682/f38e1b96-d7db-406e-8542-9a33c20ec8e2)

**Comment by Mariosutil** [comment]
Los veo bien. 
¿Qué tal os parece el de gestionar factura?

![image](https://github.com/JuliaArellano/PRACTICA_3/assets/127235455/14fa5310-2b6b-4c80-be8c-439d6b6ffdb3)

**Comment by Mariosutil** [comment]
Los veo bien.
¿Qué tal os parece el de gestionar factura?

![image](https://github.com/JuliaArellano/PRACTICA_3/assets/127235455/da7b6b03-d561-4bdb-a4ae-6d9fed38a9df)

**Comment by pgl1005** [comment]
Veo bien los vuestros, yo he hecho estos dos más, que os parecen?
<img width="412" alt="image" src="https://github.com/JuliaArellano/PRACTICA_3/assets/127233991/fa4056ac-b6fa-4a4f-9b2f-9c15b8f271c8">
<img width="410" alt="image" src="https://github.com/JuliaArellano/PRACTICA_3/assets/127233991/f3e09c59-d360-4f20-a192-1daeaadd7b57">

**Comment by Mariosutil** [comment]
Los veo muy bien Paula, yo también he hecho estos dos:

![image](https://github.com/JuliaArellano/PRACTICA_3/assets/127235455/79c3887e-6c9a-4614-9a10-5790b8860abb)

![image](https://github.com/JuliaArellano/PRACTICA_3/assets/127235455/e114abff-806f-4fd8-8fd0-1d8264b9d2c0)


¿Qué os parece?

**Comment by Lorenacalvoperez** [comment]
Yo he realizado el siguiente caso de uso:
![image](https://github.com/JuliaArellano/PRACTICA_3/assets/127235680/517abbfb-8d3a-4c6b-9655-260f7afde782)
