### ISSUE TITLE
Diagrama de casos

### ISSUE THREAD

**Issue by JuliaArellano** [JuliaArellano/PRACTICA_3#2]
Se realizara un diagrama con el caso asociado , cuyo enunciado es:  

Se necesita desarrollar el software para la gestión de una empresa dedicada a la gestión
de clínicas de salud especializada en consultas médicas. Para cada clínica, el sistema
guardará su código, su nombre comercial, dirección postal y las especialidades de las que
dispone, por ejemplo: oftalmología, aparato digestivo, sistema cardiovascular, etc. Cada
clínica tiene un director del cual queremos saber su nombre, DNI, la fecha que comenzó a
trabajar en la empresa y la fecha de inicio en el puesto actual. El director sólo puede
gestionar una única clínica a la vez. Cada clínica, además del director, tiene médicos,
graduados en enfermería, auxiliares de enfermería y un administrativo. Para todos los
empleados se guardan los datos de nombre y DNI, además del médico necesitamos saber
su especialidad y número de colegiado, de los graduados en enfermería su especialidad y
de los auxiliares de enfermería si son de ciclo de grado medio o grado superior.
Es necesario gestionar también las consultas que se producen en las clínicas. Para cada
consulta que se realiza en la clínica queremos saber: el paciente, la fecha y hora de la
consulta, la especialidad solicitada y médico asignado. Para cada paciente necesitamos
guardar su nombre, su DNI, su dirección y su cuenta bancaria si optan por el pago
domiciliado.
El administrativo será el encargado de generar la cita de los pacientes, que la pueden
solicitar presencialmente o por teléfono. Al finalizar la consulta el administrativo
gestionará la factura, el paciente podrá decidir si quiere la factura para pagarla o bien
quiere que se acumule en su cuenta personal.
Mensualmente el administrativo envía a una entidad bancaria colaboradora un fichero de
cargos domiciliados.
El importe de la factura estará en función:
   • del tipo de especialidad de la consulta,
   • los días que se ha repetido la consulta hasta que se ha realizado el diagnostico, las
sucesivas citas después de la primera son gestionadas por los auxiliares de
enfermería.
   • las pruebas necesarias que se hayan realizado, estos datos serán introducidos por
el médico especialista.
Se quiere tener un historial de consultas del paciente, por cada paciente se podrá
visualizar todas sus consultas, se mostrará día, fecha y especialidad. Estas consultas las
podrá realizar el personal médico y administrativo.
Si el paciente no está dado de alta en el sistema, el administrativo le solicitará sus datos y
creará la nueva ficha de cliente

**Comment by pgl1005** [comment]
Aquí tengo el diagrama de casos:
![Diagrama](https://github.com/JuliaArellano/PRACTICA_3/assets/127233991/5f47fd38-8623-40d6-bd35-e9cb10d4c06b)

**Comment by Lorenacalvoperez** [comment]
Diagrama completado
