### ISSUE TITLE
Catálogo de los requisitos 

### ISSUE THREAD

**Issue by JuliaArellano** [JuliaArellano/PRACTICA_3#3]
Se establecen los requisitos y se les asignara una descripción , una importancia y una prioridad.
![image](https://github.com/JuliaArellano/PRACTICA_3/assets/127235682/c25ae5b0-77dd-4d15-9488-5eeb5967965c)

**Comment by pgl1005** [comment]
Hola chicos, que os parece como idea este requisito funcional? 
<img width="396" alt="image" src="https://github.com/JuliaArellano/PRACTICA_3/assets/127233991/b50f6906-801e-4980-979c-3fb9b34658f5">

**Comment by JuliaArellano** [comment]
la veo correcta

**Comment by JuliaArellano** [comment]
Otro requisito :
![image](https://github.com/JuliaArellano/PRACTICA_3/assets/127235682/cd7874c1-fbe1-441f-b00b-418f61751fb3)

**Comment by Mariosutil** [comment]
Me parecen ambos correctos

**Comment by Mariosutil** [comment]
He considerado que este requisito sería interesante:
![image](https://github.com/JuliaArellano/PRACTICA_3/assets/127235455/8ef30715-42fc-4b7b-8bab-0c77099a0bb5)

**Comment by Lorenacalvoperez** [comment]
Otro requisito que sería interesante:
![image](https://github.com/JuliaArellano/PRACTICA_3/assets/127235680/5372f134-96e4-4fe9-b341-c2aa7dd486ec)

**Comment by Lorenacalvoperez** [comment]
Todo coorecto
