### ISSUE TITLE
Especificación de los actores del sistema

### ISSUE THREAD

**Issue by JuliaArellano** [JuliaArellano/PRACTICA_3#4]
Se muestran los diferentes tipos de usuarios y otros sistemas con los que deba interactuar el sistema a desarrollar

**Comment by pgl1005** [comment]
He realizado esta descripción sobre uno de los actores del sistema, en este caso el médico.
<img width="396" alt="image" src="https://github.com/JuliaArellano/PRACTICA_3/assets/127233991/bea40623-9713-49e0-9f92-9afd5e350a2a">

**Comment by Lorenacalvoperez** [comment]
Yo he realizado la descripción de otro de los actores, el auxiliar:
![image](https://github.com/JuliaArellano/PRACTICA_3/assets/127235680/c701ae2b-4caa-41aa-a813-20c2500a1188)

**Comment by Lorenacalvoperez** [comment]
La descripción del administrativo es la siguiente:
![image](https://github.com/JuliaArellano/PRACTICA_3/assets/127235680/0ba8fcd3-ca28-4eda-bb11-5638fa772e12)

**Comment by Lorenacalvoperez** [comment]
Tarea completada
